# Generated by Django 4.2.2 on 2023-06-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('kwota', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
