# Generated by Django 4.2.2 on 2023-06-14 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0002_faktura_user_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
        migrations.RemoveField(
            model_name='faktura',
            name='id',
        ),
        migrations.AddField(
            model_name='faktura',
            name='nr_faktury',
            field=models.AutoField(default=20230614200158, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faktura',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
